[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; base-uri 'none'; connect-src 'self' https://api.dribbble.com/v2/user/shots; font-src 'self'; img-src 'self' https://cdn.dribbble.com; manifest-src 'self'; object-src 'none'; script-src 'self' https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/ https://absorbed-andesaurus.glitch.me/; style-src 'self'" 

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  from = "/banners.html"
  to = "/design/display"
  status = 301
  from = "/ebook.html"
  to = "/design/ebook"
  status = 301
  from = "/elearning.html"
  to = "/design/elearn"
  status = 301
  from = "/recipe.html"
  to = "/design/recipe"
  status = 301
  from = "/web-management.html"
  to = "/design/web"
  status = 301
  from = "/instagram"
  to = "https://emporium.becausejulia.com/"
  status = 301


               
          
             
        
  