module.exports = async function () {
  return [
    {
      headline: "Email with Video",
      title: "Email Code",
      live: "https://ninjulia.github.io/email_html5video/",
      repo: "https://github.com/ninjulia/email_html5video/",
      image: "./assets/img/code/videoEmail.webp",
      type: "Code",
      tags: "code",
    },
    {
      headline: "Bundle Builder Tool",
      title: "Front End Web | CMS",
      live: "https://ninjulia.github.io/bundleBuilder/",
      repo: "https://github.com/ninjulia/bundleBuilder/",
      image: "./assets/img/code/bundler.webp",
      type: "Code",
      tags: "code",
    },
    {
      headline: "Speed Visualizer",
      title: "Front End Web | JQuery",
      live: "https://ninjulia.github.io/JavaScript_SpeedVisualizer/",
      repo: "https://github.com/ninjulia/JavaScript_SpeedVisualizer/",
      image: "./assets/img/code/speed.webp",
      type: "Code",
      tags: "code",
    },
    {
      headline: "Portfolio Template",
      title: "Front End Web | CMS",
      live: "https://astro-storyblock-portfolio-template.netlify.app/",
      repo: "https://github.com/ninjulia/astro-storyblok-portfolio",
      image: "./assets/img/code/template.webp",
      type: "Code",
      tags: "code",
    },
    {
      headline: "Email with Scratch-off Effect",
      title: "Email Code",
      live: "https://ninjulia.github.io/email_scratchoff/",
      repo: "https://github.com/ninjulia/email_scratchoff",
      image: "./assets/img/code/scratchoff.webp",
      type: "Code",
      tags: "code",
    },
    {
      headline: "Email with Carousel",
      title: "Email Code",
      live: "https://ninjulia.github.io/email_carousel/",
      repo: "https://github.com/ninjulia/email_carousel",
      image: "./assets/img/code/carousel.webp",
      type: "Code",
      tags: "code",
    },
  ];
};
